### PR TITLE
Simplifying the stub

### PR DESCRIPTION
**Pull request by sole**
I've done some work on this for #872676, following the discussions we had over bugzilla/irc.

Hopefully we can burninate the bug if you're OK with the changes, or at least we can start iterating (for example, replacing the 'fake' menu bar with x-menubar or the appropriate tag). I had a look at the Firefox OS style guide but I didn't copy the entire stylesheet in order to keep things simple and less overwhelming :-)

r? @fwenzel @jlongster

### CODE REVIEW

**Comment by jlongster** [comment]
Looks good, you can go ahead and remove zepto and the receipt verifier lib too. Once you do that we can merge this. r+wc

**Comment by sole** [comment]
Done! Also something in the comment was wrong (referring to id = 'install' but the actual button being 'install-btn'), so I fixed that too.

**Comment by fwenzel** [comment]
90,000 deleted lines? Yeeeeah :)

**Comment by jlongster** [comment]
Weird, I thought this said it could be merged... I'll try to do it locally

**Pull request merged**
