### PR TITLE
added sample readme template; bug 881784

### PR DESCRIPTION
**Pull request by operatorjen**

### CODE REVIEW

**Comment by operatorjen** [comment]
@jlongster r?

**Comment by jlongster** [comment]
I like the idea, and I hope people use it. It's a tiny bit confusing because it looks like there's two README's though. What do you think @sole?

**Comment by sole** [comment]
Yes, I like the idea too!

Regarding the "two readme's" issue, what about merging the contents of the README template into the actual README? So it can act as "something that works but that you can modify for your specific cases" just like the rest of the code in the template.

**Comment by tofumatt** [comment]
I like that more too. Everyone who reads the README won't always read the other sample one. Just have the regular thing, then:

```
Included is this README template for your app:

# My App Name #

[etc.]
```

**Comment by operatorjen** [comment]
Hmm rebased! Now I've consolidated it into the initial readme with a note about the sample

**Pull request merged**
